del ..\ckt.lib
cl /I..\..\include /c acan.c >> ..\..\msc.out
cl /I..\..\include /c acaskq.c >> ..\..\msc.out
cl /I..\..\include /c acsetp.c >> ..\..\msc.out
cl /I..\..\include /c cktaccpt.c >> ..\..\msc.out
cl /I..\..\include /c cktacct.c >> ..\..\msc.out
cl /I..\..\include /c cktacdum.c >> ..\..\msc.out
cl /I..\..\include /c cktask.c >> ..\..\msc.out
cl /I..\..\include /c cktaskaq.c >> ..\..\msc.out
cl /I..\..\include /c cktasknq.c >> ..\..\msc.out
cl /I..\..\include /c cktbindn.c >> ..\..\msc.out
cl /I..\..\include /c cktbkdum.c >> ..\..\msc.out
cl /I..\..\include /c cktclrbk.c >> ..\..\msc.out
cl /I..\..\include /c cktcrte.c >> ..\..\msc.out
cl /I..\..\include /c cktdelt.c >> ..\..\msc.out
cl /I..\..\include /c cktdest.c >> ..\..\msc.out
cl /I..\..\include /c cktdisto.c >> ..\..\msc.out
cl /I..\..\include /c cktdlti.c >> ..\..\msc.out
cl /I..\..\include /c cktdltm.c >> ..\..\msc.out
cl /I..\..\include /c cktdltn.c >> ..\..\msc.out
cl /I..\..\include /c cktdojob.c >> ..\..\msc.out
cl /I..\..\include /c cktdump.c >> ..\..\msc.out
cl /I..\..\include /c cktfbran.c >> ..\..\msc.out
cl /I..\..\include /c cktfdev.c >> ..\..\msc.out
cl /I..\..\include /c cktfnda.c >> ..\..\msc.out
cl /I..\..\include /c cktfndm.c >> ..\..\msc.out
cl /I..\..\include /c cktfnode.c >> ..\..\msc.out
cl /I..\..\include /c cktftask.c >> ..\..\msc.out
cl /I..\..\include /c cktgrnd.c >> ..\..\msc.out
cl /I..\..\include /c ckti2nod.c >> ..\..\msc.out
cl /I..\..\include /c cktic.c >> ..\..\msc.out
cl /I..\..\include /c cktinit.c >> ..\..\msc.out
cl /I..\..\include /c cktlnkeq.c >> ..\..\msc.out
cl /I..\..\include /c cktload.c >> ..\..\msc.out
cl /I..\..\include /c cktmapn.c >> ..\..\msc.out
cl /I..\..\include /c cktmask.c >> ..\..\msc.out
cl /I..\..\include /c cktmcrt.c >> ..\..\msc.out
cl /I..\..\include /c cktmkcur.c >> ..\..\msc.out
cl /I..\..\include /c cktmknod.c >> ..\..\msc.out
cl /I..\..\include /c cktmkvol.c >> ..\..\msc.out
cl /I..\..\include /c cktmpar.c >> ..\..\msc.out
cl /I..\..\include /c cktnames.c >> ..\..\msc.out
cl /I..\..\include /c cktnewan.c >> ..\..\msc.out
cl /I..\..\include /c cktneweq.c >> ..\..\msc.out
cl /I..\..\include /c cktnewn.c >> ..\..\msc.out
cl /I..\..\include /c cktnodn.c >> ..\..\msc.out
cl /I..\..\include /c cktnoise.c >> ..\..\msc.out
cl /I..\..\include /c cktntask.c >> ..\..\msc.out
cl /I..\..\include /c cktnum2n.c >> ..\..\msc.out
cl /I..\..\include /c cktop.c >> ..\..\msc.out
cl /I..\..\include /c cktparam.c >> ..\..\msc.out
cl /I..\..\include /c cktpmnam.c >> ..\..\msc.out
cl /I..\..\include /c cktpname.c >> ..\..\msc.out
cl /I..\..\include /c cktpzld.c >> ..\..\msc.out
cl /I..\..\include /c cktpzset.c >> ..\..\msc.out
cl /I..\..\include /c cktpzstr.c >> ..\..\msc.out
cl /I..\..\include /c cktsenac.c >> ..\..\msc.out
cl /I..\..\include /c cktsenup.c >> ..\..\msc.out
cl /I..\..\include /c cktsetap.c >> ..\..\msc.out
cl /I..\..\include /c cktsetbk.c >> ..\..\msc.out
cl /I..\..\include /c cktsetnp.c >> ..\..\msc.out
cl /I..\..\include /c cktsetup.c >> ..\..\msc.out
cl /I..\..\include /c cktsncom.c >> ..\..\msc.out
cl /I..\..\include /c cktsndct.c >> ..\..\msc.out
cl /I..\..\include /c cktsnld.c >> ..\..\msc.out
cl /I..\..\include /c cktsnprt.c >> ..\..\msc.out
cl /I..\..\include /c cktsnset.c >> ..\..\msc.out
cl /I..\..\include /c cktsopt.c >> ..\..\msc.out
cl /I..\..\include /c ckttemp.c >> ..\..\msc.out
cl /I..\..\include /c cktterr.c >> ..\..\msc.out
cl /I..\..\include /c ckttroub.c >> ..\..\msc.out
cl /I..\..\include /c ckttrunc.c >> ..\..\msc.out
cl /I..\..\include /c ckttyplk.c >> ..\..\msc.out
cl /I..\..\include /c daskq.c >> ..\..\msc.out
cl /I..\..\include /c dcoaskq.c >> ..\..\msc.out
cl /I..\..\include /c dcop.c >> ..\..\msc.out
cl /I..\..\include /c dcosetp.c >> ..\..\msc.out
cl /I..\..\include /c dctaskq.c >> ..\..\msc.out
cl /I..\..\include /c dctran.c >> ..\..\msc.out
cl /I..\..\include /c dctrcurv.c >> ..\..\msc.out
cl /I..\..\include /c dctsetp.c >> ..\..\msc.out
cl /I..\..\include /c distoan.c >> ..\..\msc.out
cl /I..\..\include /c dkerproc.c >> ..\..\msc.out
cl /I..\..\include /c dloadfns.c >> ..\..\msc.out
cl /I..\..\include /c dsetparm.c >> ..\..\msc.out
cl /I..\..\include /c naskq.c >> ..\..\msc.out
cl /I..\..\include /c nevalsrc.c >> ..\..\msc.out
cl /I..\..\include /c ninteg.c >> ..\..\msc.out
cl /I..\..\include /c noisean.c >> ..\..\msc.out
cl /I..\..\include /c nsetparm.c >> ..\..\msc.out
cl /I..\..\include /c pzan.c >> ..\..\msc.out
cl /I..\..\include /c pzaskq.c >> ..\..\msc.out
cl /I..\..\include /c pzsetp.c >> ..\..\msc.out
cl /I..\..\include /c sendest.c >> ..\..\msc.out
cl /I..\..\include /c sensetp.c >> ..\..\msc.out
cl /I..\..\include /c snaskq.c >> ..\..\msc.out
cl /I..\..\include /c snstart.c >> ..\..\msc.out
cl /I..\..\include /c sperror.c >> ..\..\msc.out
cl /I..\..\include /c tfanal.c >> ..\..\msc.out
cl /I..\..\include /c tfaskq.c >> ..\..\msc.out
cl /I..\..\include /c tfsetp.c >> ..\..\msc.out
cl /I..\..\include /c tranaskq.c >> ..\..\msc.out
cl /I..\..\include /c traninit.c >> ..\..\msc.out
cl /I..\..\include /c transetp.c >> ..\..\msc.out
lib ..\ckt.lib @response.lib
